<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A password will be generated automatically if not provided' => 'Если не задать пароль, он будет сгенерирован автоматически',
    'Account' => 'Аккаунт',
    'Account Settings' => 'Настройки аккаунта',
    'Account data updated successfully' => 'Настройки аккаунта сохранены',
    'Account details' => 'Информация об аккаунте',
    'Account details have been updated' => 'Информация об аккаунте сохранена',
    'Are you sure you want to block this user?' => 'Заблокировать этого пользователя?',
    'Are you sure you want to delete this user?' => 'Вы действительно хотите удалить этого пользователя?',
    'Are you sure you want to switch to this user for the rest of this Session?' => 'Вы будете использовать аккаунт этого пользователя до выхода. Продолжить?',
    'Are you sure you want to unblock this user?' => 'Разблокировать этого пользователя?',
    'Are you sure?' => 'Вы уверены?',
    'Assignments' => 'Права',
    'Authentication Key' => 'Ключ авторизации',
    'Become this user' => 'Притвориться этим пользователем',
    'Block' => 'Блокировать',
    'Block status' => 'Блокировка',
    'Blocked At' => 'Время блокировки',
    'Blocked at {0, date, MMMM dd, YYYY HH:mm}' => 'Заблокирован {0, date, d MMMM yyyy} в {0, date, HH:mm}',
    'Confirmed At' => 'Время подтверждения',
    'Create' => 'Создать',
    'Create a user account' => 'Создать нового пользователя',
    'Created At' => 'Время создания',
    'Credentials will be sent to the user by email' => 'Реквизиты доступа будут высланы на почту пользователя (на самом деле нет)',
    'Current Password' => 'Текущий пароль',
    'Current password is not valid' => 'Текущий пароль неверен',
    'Delete' => 'Удалить',
    'Email' => 'Email',
    'Error while trying to generate new password' => 'Не удалось сгенерировать новый пароль',
    'First Name' => 'Имя',
    'Generate and send new password to user' => 'Сгенерировать и послать на почту новый пароль',
    'ID' => 'ID',
    'Impersonate user is disabled in the application configuration' => 'Возможность переключения пользователей заблокирована в настройках',
    'Information' => 'Информация',
    'Invalid login or password' => 'Неверный логин или пароль',
    'Last Name' => 'Фамилия',
    'Login' => 'Логин',
    'Manage users' => 'Управление пользователями',
    'New Password' => 'Новый пароль',
    'New Password has been generated and sent (actually no send) to user' => 'Новый пароль был создан и отослан на почту пользователя (на самом деле нет)',
    'New permission' => 'Новое разрешение',
    'New role' => 'Новая роль',
    'New rule' => 'Новое правило',
    'New user' => 'Новый пользователь',
    'Not blocked' => 'Не заблокирован',
    'Password' => 'Пароль',
    'Password Hash' => 'Хэш пароля',
    'Password generation is not possible for admin users' => 'Невозможна автоматическая генерация пароля для администраторов',
    'Permissions' => 'Права доступа',
    'Please fix following errors:' => 'Исправьте следующие ошибки:',
    'Profile' => 'Профиль',
    'Profile Data' => 'Данные профиля',
    'Profile Data updated Successfully' => 'Профиль сохранен',
    'Profile details' => 'Данные профиля',
    'Profile details have been updated' => 'Данные профиля сохранены',
    'Profile settings' => 'Настройки профиля',
    'Remember Me' => 'Запомнить меня',
    'Roles' => 'Роли',
    'Rules' => 'Правила',
    'Save' => 'Сохранить',
    'Sign In' => 'Войти',
    'Sign in to start your session' => 'Представьтесь, пожалуйста!',
    'Unblock' => 'Разблокировать',
    'Update' => 'Редактировать',
    'Update user account' => 'Редактировать аккаунт пользователя',
    'Updated At' => 'Время обновления',
    'User NOT has been confirmed' => 'Пользователь НЕ БЫЛ подтвержден',
    'User NOT has been deleted' => 'Пользователь НЕ БЫЛ удален',
    'User has been blocked' => 'Пользователь заблокирован',
    'User has been confirmed' => 'Пользователь подтвержден',
    'User has been created' => 'Пользователь создан',
    'User has been deleted' => 'Пользователь удален',
    'User has been unblocked' => 'Пользователь разблокирован',
    'User not found' => 'Пользователь не найден',
    'User with {attribute_name} "{attribute_value}" already exist' => 'Уже существует пользователь с {attribute_name} «{attribute_value}»',
    'Username' => 'Имя пользователя',
    'Users' => 'Пользователи',
    'You can assign multiple roles or permissions to user by using the form below' => 'Вы можете назначать роли и разрешения',
    'You can not remove your own account' => 'Вы не можете удалить свой собственный аккаунт',
];
